# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- script: |
    npm -g install ganache-cli
  displayName: 'ganache-cli installation'

- script: |
    pip3 install eth-brownie
  displayName: 'eth-brownie installation'

- checkout: self
  submodules: true
  displayName: 'get submodules'

- script: |
    brownie compile
  displayName: 'smart contracts compilation'

- script: 
    brownie test
  displayName: 'test smart contracts'